GlenwoodMedicalCentre/Controllers/PatientController.cs
using GlenwoodMed.BusinessLogic;
using GlenwoodMed.BusinessLogic.Business;
using GlenwoodMed.Data;
using GlenwoodMed.Data.Tables;
using GlenwoodMed.Model;
using GlenwoodMed.Model.ViewModels;
using GlenwoodMedicalCentre.Models;
using System;
using PagedList.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using RazorPDF;
using Microsoft.Owin.Security;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity;
using System.Threading.Tasks;
using MoreLinq;
//using PagedList;

namespace GlenwoodMedicalCentre.Controllers
{
    [RequireHttps]
    public class PatientController : Controller
    {
        RegisterBusiness rg = new RegisterBusiness();
        DependentBusiness db = new DependentBusiness();
        BookingBusiness bb = new BookingBusiness();
        PatientBusiness pb = new PatientBusiness();
        StatisticsBusiness sb = new StatisticsBusiness();
        RolesBusiness rb = new RolesBusiness();
        //TestResultBusiness tb = new TestResultBusiness();
        HIVTestResultBusiness htb = new HIVTestResultBusiness();
        UploadBusiness bu = new UploadBusiness();
        ReportModel rm = new ReportModel();
        // GET: Patient
        [Authorize]
        public ActionResult Index(int? page, int? bookingId, int pageSize = 5, string patient = "")
        {

            if (Request.HttpMethod != "GET")
            {
                page = 1;
            }

            int pageNumber = (page ?? 1);

            if (bookingId.HasValue)
            {
                bb.EndConsultaion(bookingId.Value);
            }

            ViewData["CountPatients"] = bb.CountMethod().ToString();
            ViewBag.Info = bb.Consulted();
            ViewData["N_count"] = bb.NotConsulted();

            //List<PatientModel> pm = pb.GetAllPatients();
            var bop = bb.GetAllBookings().Where(x => x.Status == 0 && Convert.ToDateTime(x.start_date).Date.Day == DateTime.Now.Day
                                                                        && Convert.ToDateTime(x.start_date).Date.Month == DateTime.Now.Month
                                                                        && Convert.ToDateTime(x.start_date).Date.Year == DateTime.Now.Year).ToList();

            List<bookingPatient> bp = bop.OrderBy(x => x.time).Where(x => x.FullName.ToLower().Contains(patient.ToLower())
                                                || x.Telephone.ToLower().Contains(patient.ToLower())
                                                || x.Email.ToLower().Contains(patient.ToLower())
                                                || patient == null).ToList();

            PagedList<bookingPatient> model = new PagedList<bookingPatient>(bp, pageNumber, pageSize);
            return View("Index", bp.ToPagedList(pageNumber, pageSize));
        }

        //[HttpPost]
        //[Authorize]
        //public ActionResult Index(string patient)
        //{
        //    List<bookingPatient> _patient;
        //    if(string.IsNullOrEmpty(patient))
        //    {
        //        _patient = bb.GetAllBookings().Where(x => x.Status == 0 && Convert.ToDateTime(x.date).Day == DateTime.Now.Day).ToList();
        //    }

        //    else
        //    {
        //        _patient = bb.GetAllBookings().Where(x => x.Status == 0 && Convert.ToDateTime(x.date).Day == DateTime.Now.Day).OrderBy(x => x.FullName).Where(x => x.FullName.ToLower().Contains(patient.ToLower())
        //                                        //|| x.Surname.ToLower().Contains(patient.ToLower())
        //                                        || x.Telephone.ToLower().Contains(patient.ToLower())
        //                                        || x.Email.ToLower().Contains(patient.ToLower())
        //                                        //|| x.NationalId.ToLower().Contains(patient.ToLower())
        //                                        //|| x.Sex.ToLower().Contains(patient.ToLower())
        //                                        //|| x.MedicalAidName.ToLower().Contains(patient.ToLower())
        //                                        //|| x.MedicalAidNo.ToLower().Contains(patient.ToLower())
        //                                        || patient == null).ToList();
        //    }
        //    return View(_patient);
        //}

        //public ActionResult Index(int? page, int pageSize = 5, string patient = "")
        //{
        //    var pb = new PatientBusiness();

        //    ViewBag.Count = pb.CountMethod().ToString();

        //    if (Request.HttpMethod != "GET")
        //    {
        //        page = 1;
        //    }

        //    //int pageSize = 5;
        //    int pageNumber = (page ?? 1);

        //    var myp = pb.GetAllPatients().OrderBy(x => x.FullName).Where(x => x.FullName.ToLower().Contains(patient.ToLower())
        //                                        || x.Surname.ToLower().Contains(patient.ToLower())
        //                                        || x.Telephone.ToLower().Contains(patient.ToLower())
        //                                        || x.NationalId.ToLower().Contains(patient.ToLower())
        //                                        || x.Sex.ToLower().Contains(patient.ToLower())
        //                                        || x.MedicalAidName.ToLower().Contains(patient.ToLower())
        //                                        || x.MedicalAidNo.ToLower().Contains(patient.ToLower())
        //                                        || patient == null).ToList();


        //    List<PatientModel> pm = myp; // pb.GetAllPatients();
        //    PagedList<PatientModel> model = new PagedList<PatientModel>(pm, pageNumber, pageSize);
        //    //return View("Index", myp.ToPagedList(pageNumber, pageSize));
        //    return View(model);
        //}

        [Authorize]
        public ActionResult PrintHistory(int PatientId)
        {
            ConsultationBusiness cb = new ConsultationBusiness();
            var con = new Consultation();

            PatientConsultationDetails pd = new PatientConsultationDetails();
            // pass in Model, then View name

            //Find Patient with the associated consultation 
            pd._Consultation = cb.GetConsultations().FindAll(x => x.PatientId == PatientId).OrderByDescending(x => x.ConsultId).ToList();
            //Find patient and display details
            pd.Patient = pb.GetPatients().Find(x => x.PatientId == PatientId);
            //pd._Xray = tb.GetAll().Where(x => x.PatientId == PatientId).ToList();
            pd._HIV = htb.GetAllTest().Where(x => x.PatientId == PatientId).ToList();
            //rm._HIV = 
            // With no Model and default view name.  Pdf is always the default view name
            //return new PdfResult();
            return new PdfResult(pd, "PrintHistory");
        }

        public ActionResult Main()
        {
            ViewBag.Info = bb.Consulted();
            ViewData["N_count"] = bb.NotConsulted();
            return View();
        }

        public ActionResult Test()
        {
            return PartialView("_AgeGroup");
        }

        public ActionResult List_info()
        {
            return View();
        }
        public PartialViewResult _ConsultedPatients(int? page, int pageSize = 5, string patientpar = "")
        {

            if (Request.HttpMethod != "GET")
            {
                page = 1;
            }

            //int pageSize = 5;
            int pageNumber = (page ?? 1);
            var bop = bb.GetAllBookings().Where(x => Convert.ToDateTime(x.date).Day == DateTime.Now.Day
                                                                        && Convert.ToDateTime(x.date).Month == DateTime.Now.Month
                                                                        && Convert.ToDateTime(x.date).Year == DateTime.Now.Year).OrderBy(x => x.FullName).DistinctBy(x => x.FullName).ToList();
            int count = 0;
            foreach (var c in bop)
            {
                count++;
            }

            ViewBag.Count = count.ToString();

            if(patientpar != "")
            {
                DateTime sin = Convert.ToDateTime(patientpar);
                //List<bookingPatient> bp = bop.OrderBy(x => x.time).Where(x => Convert.ToDateTime(x.date).ToString("MM/dd/yyyy").Equals(Convert.ToDateTime(patientpar).ToString("MM/dd/yyyy"))
                //                                || patientpar == null).ToList();

                //List<bookingPatient> bp = bop.FindAll(x => DateTime.Equals(Convert.ToDateTime(x.start_date), sin)).ToList();
                List<bookingPatient> bp = bop.FindAll(x => DateTime.Equals(Convert.ToDateTime(x.start_date), sin)).ToList();

                PagedList<bookingPatient> model = new PagedList<bookingPatient>(bp, pageNumber, pageSize);
                return PartialView("_ConsultedPatients", model);
            }
            
            else
            {
                PagedList<bookingPatient> model = new PagedList<bookingPatient>(bop, pageNumber, pageSize);
                return PartialView("_ConsultedPatients", model);
            }   
        }

        public PartialViewResult _IncomeChart()
        {
            return PartialView("_Income");
        }

        public PartialViewResult _AgeChart()
        {
            return PartialView("_AgeGroup");
        }

        public PartialViewResult _ConsultationsChart()
        {
            return PartialView("_Consultations");
        }

        public JsonResult Consult()
        {
            return new JsonResult { Data = sb.ReportData(), JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        public JsonResult GetPatients(string term)
        {
            var pb = new PatientBusiness();
            DataContext da = new DataContext();
            List<string> myp;

GlenwoodMedicalCentre/Controllers/StatisticsController.cs
using GlenwoodMed.BusinessLogic.Business;
using GlenwoodMed.Data;
using GlenwoodMed.Data.Tables;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GlenwoodMedicalCentre.Controllers
{
    [RequireHttps]
    public class StatisticsController : Controller
    {
        StatisticsBusiness sb = new StatisticsBusiness();
        // GET: Statistics
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Test()
        {
            return View("AgeChart");
        }

        public ActionResult DrugChart()
        {
            return View();
        }

        public ActionResult DashBoard()
        {
            return View();
        }

        [Authorize]
        public ActionResult Main()
        {
            return View();
        }

        public ActionResult AgeChart()
        {
            return View();
        }

        public PartialViewResult AgeCht(int? number1, int? number2, int? number3)
        {
            return PartialView("_Age");
        }

        public JsonResult AgeGroup(int? number1, int? number2, int? number3)
        {
            return new JsonResult { Data = sb.AgeData(number1, number2, number3), JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        public JsonResult DrugStatus()
        {
            return new JsonResult { Data = sb.DrugData(), JsonRequestBehavior = JsonRequestBehavior.AllowGet};
        }


        public JsonResult ProfitYearSelection()
        {
            return new JsonResult { Data = sb.ProfitYear(), JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        public JsonResult ProfitMonthSelection(int year)
        {
            return new JsonResult { Data = sb.ProfitMonth(year), JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        public JsonResult ProfitDaysSelection(int year, string month)
        {
            return new JsonResult { Data = sb.ProfitDays(year, month), JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }
    }
}

GlenwoodMedicalCentre/Views/Statistics/AgeChart.cshtml
@{
    ViewBag.Title = "AgeChart";
}

<script src="~/Scripts/jquery-2.1.4.js"></script>
<script src="~/Scripts/gviz-api.js"></script>
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<link href="~/Content/ButtonColors.css" rel="stylesheet" />

<div class="text-center"><h2 class="x">Chart</h2></div>
<div class="btn-group btn-group-justified" role="group" aria-label="ButtonHeads">
    <div class="btn-group" role="group">
        <button type="button" class="btn btn-default btn-lg but" onclick="location.href='@Url.Action("Index", "Statistics")';return false;"> Profit</button>
    </div>
    <div class="btn-group" role="group">
        <button type="button" class="btn btn-danger btn-lg but" onclick="location.href='@Url.Action("AgeChart", "Statistics")';return false;"> Age Groups</button>
    </div>
</div>

<div id="chartbar" style="width:100%; height:400px">
    @*Chart loads in this div tag*@
</div>

@section scripts{
    <script>
        var chartData; //global variable for hold chart data
        google.load("visualization", "1", { packages: ["corechart"] });

        //Fill chartData below
        $(document).ready(function () {
            $.ajax({
                url: '/Statistics/AgeGroup',
                data: {},
                dataType: 'json',
                type: 'get',
                //contentType: "application/json; chartset=utf-8",
                success: function (data) {
                    chartData = data;
                },
                error: function () {
                    alert("Error loading data! Please try again.")
                }
            }).done(function () {
                //after completely loading data
                drawChart();
            })
        })

        function drawChart() {
            var data = google.visualization.arrayToDataTable(chartData);

            var options = {
                title: "Age Groups",
                pointSize: 5
            };

            var barChart = new google.visualization.ColumnChart(document.getElementById('chartbar'));
            barChart.draw(data, options);
        }
    </script>
}

GlenwoodMedicalCentre/Views/Statistics/DashBoard.cshtml
@{
    ViewBag.Title = "DashBoard";
}

<link href="~/Content/Dashboard.css" rel="stylesheet" />
<h2>DashBoard</h2>

<div class="row">
    <div class="col-sm-3 col-md-2 sidebar">
        <div class="dropup">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" id="dropdownMenu2" aria-haspopup="true" aria-expanded="false">
                <b>Actions</b>
                <span class="caret"></span>
            </button>
            <ul class="nav nav-sidebar dropdown-menu" aria-labelledby="dropdownMenu2">
                <li class="dropdown-header"><b>Primary Actions</b></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Reports</a></li>
                <li role="separator" class="divider"></li>
                <li class="dropdown-header"><b>Secondary Actions</b></li>
                <li role="separator" class="divider"></li>
            </ul>
        </div>

        <ul class="nav nav-sidebar">
            <li class="active"><a href="#">Overview <span class="sr-only">(current)</span></a></li>
            <li><a href="#">Reports</a></li>
            <li><a href="#">Analytics</a></li>
            <li><a href="#">Export</a></li>
        </ul>
        <ul class="nav nav-sidebar">
            <li><a href="">Nav item</a></li>
            <li><a href="">Nav item again</a></li>
            <li><a href="">One more nav</a></li>
            <li><a href="@Url.Action("Index", "Patient")">Another nav item</a></li>
            <li><a href="">More navigation</a></li>
        </ul>
        <ul class="nav nav-sidebar">
            <li><a href="">Nav item again</a></li>
            <li><a href="">One more nav</a></li>
            <li><a href="">Another nav item</a></li>
        </ul>
    </div>
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <h1 class="page-header">Dashboard</h1>

        <div class="row placeholders">
            <div class="col-xs-6 col-sm-3 placeholder">
                <img data-src="holder.js/200x200/auto/sky" class="img-responsive" alt="Generic placeholder thumbnail">
                <h4>Label</h4>
                <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
                <img data-src="holder.js/200x200/auto/vine" class="img-responsive" alt="Generic placeholder thumbnail">
                <h4>Label</h4>
                <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
                <img data-src="holder.js/200x200/auto/sky" class="img-responsive" alt="Generic placeholder thumbnail">
                <h4>Label</h4>
                <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
                <img data-src="holder.js/200x200/auto/vine" class="img-responsive" alt="Generic placeholder thumbnail">
                <h4>Label</h4>
                <span class="text-muted">Something else</span>
            </div>
        </div>

        <h2 class="sub-header">Section title</h2>
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Header</th>
                        <th>Header</th>
                        <th>Header</th>
                        <th>Header</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>1,001</td>
                        <td>Lorem</td>
                        <td>ipsum</td>
                        <td>dolor</td>
                        <td>sit</td>
                    </tr>
                    <tr>
                        <td>1,002</td>
                        <td>amet</td>
                        <td>consectetur</td>
                        <td>adipiscing</td>
                        <td>elit</td>
                    </tr>
                    <tr>
                        <td>1,003</td>
                        <td>Integer</td>
                        <td>nec</td>
                        <td>odio</td>
                        <td>Praesent</td>
                    </tr>
                    <tr>
                        <td>1,003</td>
                        <td>libero</td>
                        <td>Sed</td>
                        <td>cursus</td>
                        <td>ante</td>
                    </tr>
                    <tr>
                        <td>1,004</td>
                        <td>dapibus</td>
                        <td>diam</td>
                        <td>Sed</td>
                        <td>nisi</td>
                    </tr>
                    <tr>
                        <td>1,005</td>
                        <td>Nulla</td>
                        <td>quis</td>
                        <td>sem</td>
                        <td>at</td>
                    </tr>
                    <tr>
                        <td>1,006</td>
                        <td>nibh</td>
                        <td>elementum</td>
                        <td>imperdiet</td>
                        <td>Duis</td>
                    </tr>
                    <tr>
                        <td>1,007</td>
                        <td>sagittis</td>
                        <td>ipsum</td>
                        <td>Praesent</td>
                        <td>mauris</td>
                    </tr>
                    <tr>
                        <td>1,008</td>
                        <td>Fusce</td>
                        <td>nec</td>
                        <td>tellus</td>
                        <td>sed</td>
                    </tr>
                    <tr>
                        <td>1,009</td>
                        <td>augue</td>
                        <td>semper</td>
                        <td>porta</td>
                        <td>Mauris</td>
                    </tr>
                    <tr>
                        <td>1,010</td>
                        <td>massa</td>
                        <td>Vestibulum</td>
                        <td>lacinia</td>
                        <td>arcu</td>
                    </tr>
                    <tr>
                        <td>1,011</td>
                        <td>eget</td>
                        <td>nulla</td>
                        <td>Class</td>
                        <td>aptent</td>
                    </tr>
                    <tr>
                        <td>1,012</td>
                        <td>taciti</td>
                        <td>sociosqu</td>
                        <td>ad</td>
                        <td>litora</td>
                    </tr>
                    <tr>
                        <td>1,013</td>
                        <td>torquent</td>
                        <td>per</td>
                        <td>conubia</td>
                        <td>nostra</td>
                    </tr>
                    <tr>
                        <td>1,014</td>
                        <td>per</td>
                        <td>inceptos</td>
                        <td>himenaeos</td>
                        <td>Curabitur</td>
                    </tr>
                    <tr>
                        <td>1,015</td>
                        <td>sodales</td>
                        <td>ligula</td>
                        <td>in</td>
                        <td>libero</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

GlenwoodMedicalCentre/Views/Statistics/DrugChart.cshtml
@{
    ViewBag.Title = "DrugChart";
}
<script src="~/Scripts/jquery-2.1.4.js"></script>
<script src="~/Scripts/gviz-api.js"></script>
<script type="text/javascript" src="https://www.google.com/jsapi"></script>

<h2>DrugChart</h2>

<div id="chartpie" style="width:100%; height:400px">
    @*Chart loads in this div tag*@
</div>

@section scripts{
    <script>
        var chartData; //global variable for hold chart data
        google.load("visualization", "1", { packages: ["corechart"] });

        //Fill chartData below
        $(document).ready(function () {
            $.ajax({
                url: '/Statistics/DrugStatus',
                data: {},
                dataType: 'json',
                type: 'get',
                //contentType: "application/json; chartset=utf-8",
                success: function (data) {
                    chartData = data;
                },
                error: function () {
                    alert("Error loading data! Please try again.")
                }
            }).done(function () {
                //after completely loading data
                drawChart();
            })
        })

        function drawChart() {
            var data = google.visualization.arrayToDataTable(chartData);

            var options = {
                title: "Drugs Availability",
                pointSize: 5
            };

            var pieChart = new google.visualization.PieChart(document.getElementById('chartpie'));
            pieChart.draw(data, options);
        }
    </script>
}

GlenwoodMedicalCentre/Views/Statistics/Main.cshtml
@{
    ViewBag.Title = "Main";
}

<link href="~/Content/ButtonColors.css" rel="stylesheet" />

<ol class="breadcrumb">
    <li class="x"><a href="@Url.Action("Main", "Statistics")">Report</a></li>
    @*<li class="active">Register Patient</li>*@
</ol>

<div class="text-center"><h2 class="x">Choose Report Type</h2>
    <hr/>
    </div>
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-4">
        <div align="center">
            <a href="@Url.Action("Index", "Information")">
                <img src="~/Images/report(info).jpg" style="width:200px; height:200px" />
                <br />
                <b>Report Information</b>
            </a>
        </div>
    </div>

    <div class="col-md-4">
        <div align="center">
            <a href="@Url.Action("Main", "Patient")">
                <img src="~/Images/report(statistics).png" style="width:200px; height:200px" />
                <br />
                <b>Report Statistics</b>
            </a>
        </div>
    </div>
    <div class="col-md-2"></div>
</div>
@*<p>
    <button type="button" class="btn btn-success" onclick="location.href='@Url.Action("CreateMedCertificate")';return false;"><span class="glyphicon glyphicon-plus"></span>  Create</button>
</p>
<iframe name="iframe1" src='@Url.Action("Test", "Patient")' width="75%" height="500" frameborder="0"></iframe>
@*<iframe src="@Html.Display("item")" width="640px" height="500px" frameborder="0"></iframe>*@
@*<iframe name="iframe1" src="target.html"></iframe>

<a href="@Url.Action("PrintAllConsultations", "Information")" target="iframe1">Open Link</a>
<a href="@Url.Action("Main", "Patient")" target="iframe1">Open Link</a>*@

GlenwoodMedicalCentre/Views/Statistics/_Profit.cshtml
<div id="chart" align="center" style="width:100%; height:300px">

</div>

@section scripts{
    <script>
        var chartDataYear;
        var chartDataMonth;
        var chartDataDays;
        var GlobalYear;
        var CurrentReport;
        google.load("visualization", "1", { packages: ["corechart"] });

        //load Profit Year report as default load
        $(document).ready(function () {
            $.ajax({
                url: '/Statistics/ProfitYearSelection',
                type: 'get',
                dataType: 'json',
                data: {},
                success: function (d) {
                    chartDataYear = d;
                },
                error: function () {

                }
            }).done(function () {
                CurrentReport = 'year';
                generateChart(chartDataYear, "Consultation Report Data '", selectYear);
            });
        }); //This would display only the years on the chart which is our default display

        function generateChart(chartData, title, selectEvent) //Method to construct chart
        {
            var data = google.visualization.arrayToDataTable(chartData);
            var options = {
                title: title,
                legend: 'none',
                colors: ['red'],
                lineWidth: 3,
                pointSize: 5,
                focusTarget: "category",
                hAxis: {showTextEvery: 1}
            }

            var linechart = new google.visualization.LineChart(document.getElementById('chart')); // chart to div tag
            if(selectEvent != null)
            {
                google.visualization.events.addListener(linechart, 'select', function() {
                    selectEvent(linechart, data);
                    });
            }

            GenerateBack(CurrentReport);
            linechart.draw(data, options); //draws the draph of the chart
        }

        function GenerateBack(currentReport) { //Method for creating a back to default button
            $('.backbuttoncontainer').remove();

            //create new back button
            if(currentReport != 'year') //back button except year according to the currentreport in the done function
            {
                //constructing the back button
                var $back = $('<button/>')
                            .text('Back')
                            .addClass('reportBack')
                            .css({ 'color': 'blue'})
                            .click(function () {
                                switch (currentReport) {
                                    case 'month':
                                        CurrentReport = 'year';
                                        generateChart(chartDataYear, "Consultation Report Data '", selectYear);
                                        break;

                                    case 'days':
                                        CurrentReport = 'month';
                                        generateChart(chartDataMonth, "Consultation Report Data of year '" + GlobalYear, selectMonth);
                                        break;
                                    default:
                                }
                                $(this).parent().remove();
                            });

                var $div = $('<div/>')
                        .addClass('backbuttoncontainer')
                        .css({ 'width': '70%', 'text-align': 'right', 'padding': '5px' })
                        .append($back);
                $('#chart').before($div);
            }
        }

        function selectYear(chart, data)
        {
            //YearEvent ( after select year data from chart )
            var selectedItem = chart.getSelection()[0];
            if (selectedItem) {
                var rowlevel = parseInt(data.getValue(selectedItem.row, 0));
                var chartData = null;

                $.ajax({
                    url: '/Statistics/ProfitMonthSelection',
                    type: 'get',
                    dataType: 'json',
                    data: {'year': rowlevel},
                    success: function (d) {
                        chartDataMonth = d;
                    },
                    error: function () {
                        alert("Error !");
                    }
                }).done(function () {
                    CurrentReport = 'month';
                    GlobalYear = rowlevel;
                    generateChart(chartDataMonth, "Consultation Report Data of year " + rowlevel, selectMonth);
                });
            }
        }

        function selectMonth(chart, data) {
            //MonthEvent ( after select month data from chart
            //Load Chart Day Wise
            var selectedItem = chart.getSelection()[0];
            if(selectedItem)
            {
                var rowlevel = data.getValue(selectedItem.row, 0);
                $.ajax({
                    url: '/Statistics/ProfitDaysSelection',
                    type: 'get',
                    dataType: 'json',
                    data: { 'year': GlobalYear, 'month': rowlevel },
                    success: function (d) {
                        chartDataDays = d;
                    },
                    error: function () {
                        alert("Error !");
                    }
                }).done(function () {
                    CurrentReport = 'days';
                    generateChart(chartDataDays, "Consultation report data of " + rowlevel + " '" + GlobalYear, null);
                })
            }
        }
    </script>


}