GlenwoodMedicalCentre/Controllers/DrugsController.cs
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using GlenwoodMed.BusinessLogic;
using GlenwoodMed.BusinessLogic.Business;
using GlenwoodMed.Data;
using PagedList;
using GlenwoodMed.Data.Tables;
using GlenwoodMed.Model.ViewModels;
using System;
using System.Collections.Generic;
using GlenwoodMed.Model;


namespace GlenwoodMedicalCentre.Controllers
{
    [RequireHttps]
    public class DrugsController : Controller
    {
        DataContext db = new DataContext();
        DrugBusiness dbo = new DrugBusiness();
        //[AcceptVerbs(HttpVerbs.Post)]
        //public JsonResult AutoComplete(string term)
        //{
        //    //var result = new List<KeyValuePair<string, string>>();
        //    var result = (from auto in db.Drugs where auto.DrugName.ToLower().Contains(term.ToLower()) select new { auto.DrugName }).Distinct();
        //    return Json(result, JsonRequestBehavior.AllowGet);
        //}

        public JsonResult searchdrug(string term)
        {
            var drugname = (from r in db.Drugs
                            where r.DrugName.ToLower().Contains(term.ToLower())
                            select new { r.DrugName }).Distinct();

           return Json(drugname, JsonRequestBehavior.AllowGet);
        }

        public JsonResult searchdrugprop(string term)
        {
            var drugname = (from r in db.Drug_Properties
                            where r.DrugCode.ToLower().Contains(term.ToLower())
                            select new { r.DrugCode, r.DrugName }).Distinct();

            return Json(drugname, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult SDrugs(int? page, int pageSize = 5, string drugpar = "")
        {
            if (Request.HttpMethod != "GET")
            {
                page = 1;
            }

            //int pageSize = 5;
            int pageNumber = (page ?? 1);


            List<DrugModel> alldrugs = dbo.GetAll().OrderBy(x => x.DrugCode).ThenBy(x => x.DrugType).Where(x => x.DrugName.ToLower().Contains(drugpar.ToLower()) ||
                                                   drugpar == null).ToList();

            PagedList<DrugModel> model = new PagedList<DrugModel>(alldrugs, pageNumber, pageSize);
            //return View("MainIndex", model);
            return PartialView("_SDrug", model);
        }

        //
        [Authorize]
        public ActionResult Details(int? id)
        {
            var dbo = new DrugBusiness();
            return PartialView(dbo.DetailsMethod(id));
        }
        [Authorize]
        public ActionResult Create()
        {
            var dbo = new DrugBusiness();

            //return View();
            return PartialView();
        }


        [HttpPost]
        [Authorize]
        public ActionResult Create(DrugModel model, string DrugType)
        {
            try
            {
                var dbo = new DrugBusiness();

                if(dbo.nameexists(model.DrugCode, DrugType))
                {
                    ModelState.AddModelError("", "Drug already exists, you can only increase quantity & change price for drug");
                    return View(model);
                }

                dbo.CreateMethod(model, DrugType);
                foreach (DrugModel dg in dbo.GetAll())
                {
                    ViewBag.DrugName = dg.DrugName;
                }
                //TempData["msg"] = "Data has been successfully saved";
                return RedirectToAction("Index");

            }
            catch (DataException)
            {

                return View(model);
            }
        }
        [Authorize]
        public ActionResult Update(int id)
        {
            var dbo = new DrugBusiness();
            return PartialView(dbo.GetReviewMethod(id));
        }

        [HttpPost]
        [Authorize]
        public ActionResult Update(int id, DrugModel model)
        {
            try
            {
                var dbo = new DrugBusiness();

                dbo.PostReviewMethod(model);
                TempData["msg"] = "Data has been successfully Updated";
                return RedirectToAction("Index");

            }
            catch
            {

                return View();
            }
        }
        //[Authorize]
        //public ActionResult Delete(int id)
        //{

        //    var dbo = new DrugBusiness();
        //    return PartialView(dbo.GetDeleteMethod(id));
        //}

        //[HttpPost]//, ActionName("Delete")]
        [Authorize]
        public ActionResult Delete(int id, DrugModel model)
        {
            try
            {
                var dbo = new DrugBusiness();
                dbo.PostDeleteMethod(id);
                TempData["msg"] = "Data has been Deleted";
                return RedirectToAction("Index");

            }
            catch
            {
                return View();
            }
        }
    }
}

GlenwoodMedicalCentre/Controllers/SearchController.cs
using GlenwoodMed.BusinessLogic;
using GlenwoodMed.BusinessLogic.Business;
using GlenwoodMed.Data;
using GlenwoodMed.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
using GlenwoodMed.Model.ViewModels;

namespace GlenwoodMedicalCentre.Controllers
{
    [RequireHttps]
    public class SearchController : Controller
    {
        PatientBusiness pb = new PatientBusiness();
        DrugBusiness db = new DrugBusiness();
        RegisterBusiness rb = new RegisterBusiness();
        ConsultationBusiness cb = new ConsultationBusiness();
        //
        // GET: /Search/
        [Authorize]
        public ActionResult GeneralSearch()
        {
            return View();
        }


        #region
        //[Authorize]
        public PartialViewResult SPatient(int? page, int pageSize = 10, string patientpar = "")
        {
            if (Request.HttpMethod != "GET")
            {
                page = 1;
            }

            //int pageSize = 5;
            int pageNumber = (page ?? 1);

            var patients = pb.GetAllPatients().ToList();
            List<PatientModel> mode =  pb.GetAllPatients().Where(x => x.FullName.ToLower().Contains(patientpar.ToLower()) ||
                                                    x.Surname.ToLower().Contains(patientpar.ToLower()) ||
                                                    x.Telephone.ToLower().Contains(patientpar.ToLower()) ||
                                                    x.NationalId.ToLower().Contains(patientpar.ToLower()) ||
                                                    x.Sex.ToLower().Contains(patientpar.ToLower()) ||
                                                    patientpar == null).ToList();

            PagedList<PatientModel> model = new PagedList<PatientModel>(mode, pageNumber, pageSize);
            //return View("_SearchPatient", bp.ToPagedList(pageNumber, pageSize));
            return PartialView("_SearchPatient", model);
        }
        #endregion

        public PartialViewResult SearchPatient(string patientpar = "")
        {
            var patients = pb.GetAllPatients().ToList();

            return PartialView(pb.GetAllPatients().Where(x => x.FullName.ToLower().Contains(patientpar.ToLower()) ||
                                                    x.Surname.ToLower().Contains(patientpar.ToLower()) ||
                                                    x.Telephone.ToLower().Contains(patientpar.ToLower()) ||
                                                    x.NationalId.ToLower().Contains(patientpar.ToLower()) ||
                                                    x.Sex.ToLower().Contains(patientpar.ToLower()) ||
                                                    patientpar == null).ToList());

        }

        #region
        //public JsonResult SPatient(string term = "")
        //{
        //    //var patients = pb.GetAllPatients().ToList();

        //    List<string> patients;

        //    patients = pb.GetAllPatients().Where(x => x.FullName.ToLower().StartsWith(term.ToLower())).Select(y => y.FullName).ToList();
        //    patients = pb.GetAllPatients().Where(x => x.Surname.ToLower().Contains(term.ToLower())).Select(y => y.Surname).ToList();
        //    patients = pb.GetAllPatients().Where(x =>x.Telephone.ToLower().Contains(term.ToLower())).Select(y => y.Telephone).ToList();
        //    patients = pb.GetAllPatients().Where(x =>x.NationalId.ToLower().Contains(term.ToLower())).Select(y => y.NationalId).ToList();
        //    patients = pb.GetAllPatients().Where(x =>x.Sex.ToLower().Contains(term.ToLower())).Select(y => y.Sex).ToList();
        //    patients = pb.GetAllPatients().Where(x =>x.MedicalAidName.ToLower().Contains(term.ToLower())).Select(y => y.MedicalAidName).ToList();
        //    patients = pb.GetAllPatients().Where(x =>x.MedicalAidNo.ToLower().Contains(term.ToLower())).Select(y => y.MedicalAidNo).ToList();

        //    return View("_SearchPatient", patients, JsonRequestBehavior.AllowGet);

        //}
        #endregion

        #region
        // [Authorize(Roles = "Pharmacist")]
        [Authorize]
        public PartialViewResult SearchDrugs(string drugpar = "")
        {
            var drugs = db.GetAll().ToList();
            return PartialView(db.GetAll().Where(x => x.DrugName.ToLower().Contains(drugpar.ToLower()) ||
                                                   x.DrugCategory.ToLower().Contains(drugpar.ToLower()) || 
                                                   drugpar == null).ToList());
        }
        #endregion


        #region
        //[Authorize(Roles="Doctor")]
        [Authorize]
        public PartialViewResult SearchStaffs(string staffpar = "")
        {
            var stuffs = rb.GetAllPatients().ToList();
            return PartialView(rb.GetAllPatients().Where(x => x.FullName.ToLower().Contains(staffpar.ToLower()) ||
                                                                    x.Surname.ToLower().Contains(staffpar.ToLower()) ||
                                                                    x.NationalId.ToLower().Contains(staffpar.ToLower()) ||
                                                                    x.Telephone.ToLower().Contains(staffpar.ToLower()) ||
                                                                    staffpar == null).ToList());
            
        }
        #endregion


        //#region
        //[Authorize]
        //public PartialViewResult SearchConsultation(string illpar = "")
        //{
        //    var cons = cb.GetConsultations().ToList();
        //    return PartialView(cb.GetConsultations().Where(x => x.illness.ToLower().Contains(illpar.ToLower()) ||
        //                                                        Convert.ToString(x.ConsultDate).Contains(illpar) ||
        //                                                        illpar == null).ToList());

        //}
        //#endregion


    }
}

GlenwoodMedicalCentre/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Glenwood Medical Centre</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/themes/base/css")
    @Scripts.Render("~/bundles/jquery")
    @*@Scripts.Render("~/bundles/jqueryval")*@
    @*@Scripts.Render("~/bundles/bootstrap")*@
    @Scripts.Render("~/bundles/jqueryui")

    <script src="~/Scripts/knockout-3.3.0.debug.js"></script>
    <script src="~/Scripts/knockout-3.3.0.js"></script>
    <style>
        body {
            /*background-color: whitesmoke;*/
            padding-top: 170px;
        }
    </style>
    @*<style>
        .modal-content {
            width: 1000px !important;
            margin: 30px auto !important;
            height: 700px;
        }

        .modal-body {
            width: 1000px !important;
            margin: 30px auto !important;
            height: 700px;
        }
    </style>*@

    <script type="text/javascript">
        $(document).ready(function () {
            $('.nav li').click(function () {
                $(this).addClass('active');
            });
        });

        $(document).ready(function () {
            $('.nav li').find('a[href="' + location.pathname + '"]')
                .closest('li').addClass('active');
        });
    </script>
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">@*container*@
            <div class="masthead">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                @*@model GlenwoodMed.Model.LoginModel*@
            
                @*<div id="navbar" >
                    <form class="navbar-form navbar-right">
                       @using (Html.BeginForm("LayoutLogin", "MyAccount", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post))
                        {
                        
                        <div class="form-group">
                            @Html.TextBox("username", " ", new { @placeholder = "Username", @class = "form-control" })
                            <input type="text" placeholder="Email" name="username" class="form-control">
                        </div>
                        <div class="form-group">
                            @Html.TextBox("password", " ", new { @placeholder = "Password", @class = "form-control" })
                            <input type="password" placeholder="Password" name="password" class="form-control">
                        </div>
                        <button type="submit" class="btn btn-success">Sign in</button>
                        }
                    </form>
                </div>/.navbar-collapse*@ 
            

                <span><img style="width:50px; height:50px" src="~/Images/white_caduceus_red_box.png" alt="Brand" />@Html.ActionLink("Glenwood Medical Centre", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })</span>
                @Html.Partial("_LoginPartial")
            </div>
            @if (Request.IsAuthenticated && User.IsInRole("Doctor"))
            {
                <nav>
                    <ul class="nav nav-pills nav-justified navbar-collapse collapse">
                        <li><a href='@Url.Action("EditProfile", "MyAccount")'><img style="width:50px; height:50px;" src="~/Images/profile_icon.png" /><br /> Profile</a></li>
                        <li><a href='@Url.Action("AddTestResult", "TestResult")'><img style="width:50px; height:50px;" src="~/Images/test.jpg" /><br /> Test</a></li>
                        <li><a href='@Url.Action("Index", "Calendar")'><img style="width:50px; height:50px;" src="~/Images/booking.png" /><br /> Calendar</a></li>
                        <li id="Patient"><a href='@Url.Action("Index", "Patient")'><img style="width:50px; height:50px;" src="~/Images/patients.png" /><br /> Patient</a></li>
                        @*<li><a href='@Url.Action("ViewDrugsConsultation", "Consultations")'> <img style="width:50px; height:50px;" src="~/Images/pharmacist-clipart-prescription-plain.png" /><br /> Pharmacist</a></li>*@
                        <li><a href='@Url.Action("MainIndex", "Consultations")'><img style="width:50px; height:50px;" src="~/Images/consultation_med.jpg" /><br /> Consultation</a></li>
                        <li><a href='@Url.Action("Create", "Email_services1")'><img style="width:50px; height:50px;" src="~/Images/email.png" /><br /> Mail</a></li>
                        @*<li><a href='@Url.Action("Index", "Home")'><img style="width:50px; height:50px;" src="~/Images/medical payment.jpg" /><br /> Medical Aid</a></li>*@
                        <li><a href='@Url.Action("GeneralSearch", "Search")'><img style="width:50px; height:50px;" src="~/Images/Search.png" /><br /> Search</a></li>
                        <li><a href='@Url.Action("Index", "Drugs")'><img style="width:50px; height:50px;" src="~/Images/drugs.jpg" /><br /> Drugs</a></li>
                        <li><a href='@Url.Action("Download", "UploadFile")'><img style="width:50px; height:50px;" src="~/Images/skype-bisiness-ico.png" /><br /> Files</a></li>
                        <li><a href='@Url.Action("Main", "Statistics")'><img style="width:50px; height:50px;" src="~/Images/icon-statistics.png" /><br /> Report</a></li>
                    </ul>
                </nav>
            }
            
            @if (Request.IsAuthenticated && User.IsInRole("Pharmacist"))
            {
                <nav>
                    <ul class="nav nav-pills nav-justified navbar-collapse collapse">
                        <li><a href='@Url.Action("EditProfile", "MyAccount")'><img style="width:50px; height:50px;" src="~/Images/profile_icon.png" /><br /> Profile</a></li>
                        <li><a href='@Url.Action("ViewDrugsConsultation", "Consultations")'> <img style="width:50px; height:50px;" src="~/Images/pharmacist-clipart-prescription-plain.png" /><br /> Pharmacist</a></li>
                        <li><a href='@Url.Action("Create", "Email_services1")'><img style="width:50px; height:50px;" src="~/Images/email.png" /><br /> Mail</a></li>
                        <li><a href='@Url.Action("GeneralSearch", "Search")'><img style="width:50px; height:50px;" src="~/Images/Search.png" /><br /> Search</a></li>
                        <li><a href='@Url.Action("Index", "Drugs")'><img style="width:50px; height:50px;" src="~/Images/drugs.jpg" /><br /> Drugs</a></li>
                    </ul>
                </nav>
            }
            
            @if (Request.IsAuthenticated && User.IsInRole("Receptionist"))
            {
                <nav>
                    <ul class="nav nav-pills nav-justified navbar-collapse collapse">
                        <li><a href='@Url.Action("EditProfile", "MyAccount")'><img style="width:50px; height:50px;" src="~/Images/profile_icon.png" /><br /> Profile</a></li>
                        @*<li><a href='@Url.Action("AddTestResult", "TestResult")'><img style="width:50px; height:50px;" src="~/Images/test.jpg" /><br /> Test</a></li>*@
                        @*<li><a href='@Url.Action("Index", "Booking")'><img style="width:50px; height:50px;" src="~/Images/booking.png" /><br /> Bookings</a></li>*@
                        <li><a href='@Url.Action("Index", "Calendar")'><img style="width:50px; height:50px;" src="~/Images/booking.png" /><br /> Calendar</a></li>
                        <li><a href='@Url.Action("Index", "Booking")'><img style="width:50px; height:50px;" src="~/Images/patients.png" /><br /> Patient</a></li>
                        @*<li><a href='@Url.Action("MainIndex", "Consultations")'><img style="width:50px; height:50px;" src="~/Images/consultation_med.jpg" /><br /> Consultation</a></li>*@
                        <li><a href='@Url.Action("Create", "Email_services1")'><img style="width:50px; height:50px;" src="~/Images/email.png" /><br /> Mail</a></li>
                        <li><a href='@Url.Action("GeneralSearch", "Search")'><img style="width:50px; height:50px;" src="~/Images/Search.png" /><br /> Search</a></li>
                        @*<li><a href='@Url.Action("Index", "Drugs")'><img style="width:50px; height:50px;" src="~/Images/drugs.jpg" /><br /> Drugs</a></li>*@
                        <li><a href='@Url.Action("Download", "UploadFile")'><img style="width:50px; height:50px;" src="~/Images/skype-bisiness-ico.png" /><br /> Files</a></li>
                        @*<li><a href='@Url.Action("Index", "Statistics")'><img style="width:50px; height:50px;" src="~/Images/icon-statistics.png" /><br /> Statistics</a></li>*@
                    </ul>
                </nav>
            }
        </div>
    </div>
    <div class="container-fluid body-content">
        @Html.Partial("Notifications")
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Glenwood Medical Centre</p>
        </footer>
    </div>

    @*@Scripts.Render("~/bundles/jquery")*@
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <div id="modal-container" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-content">
        </div>
    </div>

    <script type="text/javascript">
        $(function () {
            // Initialize numeric spinner input boxes
            //$(".numeric-spinner").spinedit();

            // Initalize modal dialog
            // attach modal-container bootstrap attributes to links with .modal-link class.
            // when a link is clicked with these attributes, bootstrap will display the href content in a modal dialog.
            $('body').on('click', '.modal-link', function (e) {
                e.preventDefault();
                $(this).attr('data-target', '#modal-container');
                $(this).attr('data-toggle', 'modal');
            });

            // Attach listener to .modal-close-btn's so that when the button is pressed the modal dialog disappears
            $('body').on('click', '.modal-close-btn', function () {
                $('#modal-container').modal('hide');
            });

            //clear modal cache, so that new content can be loaded
            $('#modal-container').on('hidden.bs.modal', function () {
                $(this).removeData('bs.modal');
            });

            $('#CancelModal').on('click', function () {
                return false;
            });
        });
    </script>
</body>
</html>

GlenwoodMedicalCentre/Views/Shared/_PdfHeader.cshtml
<img src="@Server.MapPath("~/Content/white_caduceus_red_box.png")" width="100" height="100" />

GlenwoodMedicalCentre/Views/Shared/_PdfLayout.cshtml
<itext creationdate="@DateTime.Now.ToString()" producer="RazorPDF">
    @RenderBody()
</itext>

GlenwoodMedicalCentre/Views/Shared/_SearchDrug.cshtml
<link href="~/Content/PagedList.css" rel="stylesheet" />
@model PagedList.IPagedList<GlenwoodMed.Model.ViewModels.DrugModel>
@using PagedList.Mvc
@using PagedList;
<table class="table table-striped table-bordered table-hover table-responsive">
    <tr class="success">
        <th>
            @Html.DisplayNameFor(model => model.First().DrugCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().DrugName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().DrugCategory)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().DrugDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Quantity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Supplier)

        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().ExpiryDate)
        </th>
        <th>

            @Html.DisplayNameFor(model => model.First().Status)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DrugCode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DrugName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DrugCategory)
            </td>
            <td>
                @Html.Raw(item.DrugDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Supplier)

            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExpiryDate)
            </td>
            <td>

                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>

                <div class="btn-group" role="group">
                    @Html.ActionLink(" ", "Update", "Drugs", new { id = item.DrugId }, new { title = "Edit " + item.DrugName + " Details" + "", @class = "lnkEdit btn btn-default glyphicon glyphicon-edit edit view" })
                    @Html.ActionLink(" ", "Details", "Drugs", new { id = item.DrugId }, new { title = "View " + item.DrugName + " Details", @class = "lnkDetail btn btn-default glyphicon glyphicon-eye-open details view" })
                    @Html.ActionLink(" ", "Delete", "Drugs", new { id = item.DrugId }, new { title = "Delete " + item.DrugName + " Details", @class = "lnkDelete btn btn-default glyphicon glyphicon-remove delete view" })
                </div>
                @*@Html.ActionLink("Update", "Update", "Drugs", new { id = item.DrugId }, new { @class = "lnkEdit btn btn-info glyphicon glyphicon-edit" })
                    @Html.ActionLink("Details", "Details", "Drugs", new { id = item.DrugId }, new { @class = "lnkDetail btn btn-info glyphicon glyphicon-eye-open" })
                    @Html.ActionLink("Delete", "Delete", "Drugs", new { id = item.DrugId }, new { @class = "lnkDelete btn btn-info glyphicon glyphicon-trash" })
                    </div>*@
            </td>

        </tr>
    }

</table>

<div align="center">
    @Html.PagedListPager(Model, page => Url.Action("Search", new { page, pagesize = Model.PageSize }))

    <b>Showing @Model.FirstItemOnPage to @Model.LastItemOnPage of @Model.TotalItemCount Patients</b>
</div>

GlenwoodMedicalCentre/Views/Shared/_SearchPatient.cshtml
@*@model IEnumerable<GlenwoodMed.Model.ViewModels.PatientModel>*@

@model IPagedList<GlenwoodMed.Model.ViewModels.PatientModel>
@using PagedList.Mvc
@using PagedList;
@using (Ajax.BeginForm("SPatient", "Search", null, new AjaxOptions() 
                                            {   HttpMethod = "GET", 
                                                UpdateTargetId = "Display", 
                                                InsertionMode = InsertionMode.Replace 
                                            }))
{
    <div align="center">
        @Html.TextBox("patientpar", "", new { @class = "form-control", @placeholder = "Enter Text Here" }) <br/>
        <input type="submit" name="searchpatient" value="Search" class="btn btn-success" />
    </div>
}
<br /><br /><br />

<table class="table table-striped table-bordered table-hover table-responsive" id="DisplayT">
    <tr class="success body-content">
        <th>
            @Html.DisplayNameFor(model => model.First().FullName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Surname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().NationalId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Sex)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.First().Telephone)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                <a href="@Url.Action("ViewPatient", "Patient", new { PatientId = item.userId })"> @Html.DisplayFor(modelItem => item.FullName) </a>
            </td>
            <td>
                <a href="@Url.Action("ViewPatient", "Patient", new { PatientId = item.userId })"> @Html.DisplayFor(modelItem => item.Surname) </a>
            </td>
            <td>
                <a href="@Url.Action("ViewPatient", "Patient", new { PatientId = item.userId })"> @Html.DisplayFor(modelItem => item.NationalId) </a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Sex)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Telephone)
            </td>
            <td>
                <div class="btn-group media-right">
                    @Html.ActionLink("View", "ViewPatient", "Patient", new { PatientId = item.userId }, new { @class = "btn btn-success" })
                    <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        <span class="caret"></span>
                        <span class="sr-only">Toggle Dropdown</span>
                    </button>

                    <ul class="dropdown-menu" role="menu">
                        <li><a href="@Url.Action("Index", "UploadFile", new { PatientId = item.userId })">Upload</a></li>
                        @*<li><a href="@Url.Action("Create", "PatientDependent", new { PatientId = item.userId })">Add Dependent</a></li>
                            <li><a href="#" onclick="location.href='@Url.Action("Index", "UploadFile", new { PatientId = item.userId, @class = "lnkEdit" })'">Something</a></li>
                            <li>@*<a href="@Html.ActionLink("Index", "UploadFile", new { PatientId = item.userId }, new { @class = "lnkEdit" })">File</a></li>*@
                        @*<li>@Html.ActionLink("File", "Index", "UploadFile", new { PatientId = item.userId,  @class = "lnkEdit" })</li>*@
                        @*<li class="divider"></li>
                        <li><a href="#">link</a></li>*@
                    </ul>
                </div>
                @*@Html.ActionLink("View", "ViewPatient", "Patient", new { PatientId = item.userId }, new { @class = "btn btn-success" })*@
            </td>
        </tr>
    }

</table>

<div align="center">
    @Html.PagedListPager(Model, page => Url.Action("SPatient", new { page, pagesize = Model.PageSize }), PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions() { HttpMethod = "GET", UpdateTargetId = "Display" }))

    <b>Showing @Model.FirstItemOnPage to @Model.LastItemOnPage of @Model.TotalItemCount Patients</b>
</div>